# Generated by Django 6.0.2 on 2026-02-27 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('source_text', models.TextField(help_text='The raw input text or extracted document text.')),
                ('fact_sheet', models.JSONField(blank=True, help_text='Structured facts extracted by Agent 1.', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('researching', 'Researching'), ('writing', 'Writing'), ('reviewing', 'Reviewing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='AgentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_name', models.CharField(help_text="e.g., 'Agent 1 (Research)', 'System'", max_length=50)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='campaigns.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='ContentPiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('blog', 'Blog Post'), ('social', 'Social Media Thread'), ('email', 'Email Teaser')], max_length=20)),
                ('content', models.TextField(help_text='The generated markdown content.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('rejected', 'Rejected by Editor'), ('approved', 'Approved by Editor')], default='draft', max_length=20)),
                ('editor_feedback', models.TextField(blank=True, help_text='Correction notes from Agent 3 or the User.', null=True)),
                ('iteration_count', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces', to='campaigns.campaign')),
            ],
        ),
    ]
